apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: proxy
spec:
  selector:
    app: printer-proxy-app
  ports:
    - port: 7777
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: backup-proxy-service
  namespace: proxy
spec:
  selector:
    app: backup-proxy-app
  ports:
    - port: 7777
      targetPort: 80
